# Generated by Django 6.0.1 on 2026-02-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.IntegerField(max_length=6),
        ),
    ]
