# Generated by Django 6.0.1 on 2026-02-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_user_statistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='no_succces_task',
        ),
        migrations.AddField(
            model_name='statistic',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statistic',
            name='no_succes_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='count_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='success_task',
            field=models.IntegerField(default=0),
        ),
    ]
